# Generated by Django 2.0.4 on 2018-05-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish_items',
            old_name='name',
            new_name='item_name',
        ),
    ]
